name: Badges

on:
  schedule:
    - cron: '24 03 * * 3'
  workflow_dispatch:

permissions: {}

jobs:
  downloads:
    name: Docker pulls
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get package downloads
        id: downloads
        uses: ./misc/action/package-downloads
        with:
          url: ${{ github.server_url }}
          repo: ${{ github.repository }}
          package: publish-unit-test-result-action

      - name: Create badge
        uses: emibcn/badge-action@4209421db54c8764d8932070ffd0f81715a629bf
        with:
          label: Docker pulls
          status: ${{ steps.downloads.outputs.total_downloads }} (${{ steps.downloads.outputs.recent_downloads_per_day }}/day)
          color: blue
          path: downloads.svg

      - name: Upload badge to Gist
        uses: andymckay/append-gist-action@6e8d64427fe47cbacf4ab6b890411f1d67c07f3e
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gistURL: https://gist.githubusercontent.com/EnricoMi/612cb538c14731f1a8fefe504f519395
          file: downloads.svg

  workflows:
    name: Dependent workflows
    runs-on: ubuntu-latest
    permissions:
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch workflows
        id: workflows
        uses: ./misc/action/fetch-workflows

      - name: Create badge
        uses: emibcn/badge-action@4209421db54c8764d8932070ffd0f81715a629bf
        with:
          label: GitHub Workflows
          status: ${{ steps.workflows.outputs.total_workflows }}
          color: blue
          path: workflows.svg

      - name: Upload badge to Gist
        uses: andymckay/append-gist-action@6e8d64427fe47cbacf4ab6b890411f1d67c07f3e
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gistURL: https://gist.githubusercontent.com/EnricoMi/612cb538c14731f1a8fefe504f519395
          file: workflows.svg
