name: Test Results (reference)

on:
  workflow_run:
    workflows: ["CI/CD"]
    types:
      - completed
permissions: {}

jobs:
  test-results:
    name: Test Results (reference)
    if: github.event.workflow_run.conclusion != 'skipped'
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Download and Extract Artifacts
        uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615
        with:
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts

      - name: Publish Test Results
        id: test-results
        uses: EnricoMi/publish-unit-test-result-action/composite@master
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          check_name: Test Results (reference)
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
          check_run_annotations_branch: "master, master-1.x, devel-1.0, devel-2.0"
          files: "artifacts/**/*.xml"
          log_level: DEBUG

      - name: Set badge color
        if: github.event.workflow_run.event != 'schedule'
        run: |
          case ${{ fromJSON( steps.test-results.outputs.json ).conclusion }} in
            success)
              echo "BADGE_COLOR=31c653" >> $GITHUB_ENV
              ;;
            failure)
              echo "BADGE_COLOR=800000" >> $GITHUB_ENV
              ;;
            neutral)
              echo "BADGE_COLOR=696969" >> $GITHUB_ENV
              ;;
          esac
        shell: bash

      - name: Create badge
        if: github.event.workflow_run.event != 'schedule'
        uses: emibcn/badge-action@4209421db54c8764d8932070ffd0f81715a629bf
        with:
          label: Tests
          status: '${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.tests }} tests, ${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.runs }} runs: ${{ fromJSON( steps.test-results.outputs.json ).conclusion }}'
          color: ${{ env.BADGE_COLOR }}
          path: tests.svg

      - name: Upload badge to Gist
        # Upload only for master branch and not for scheduled event
        if: >
          github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'master' && github.event.workflow_run.event != 'schedule'
        uses: andymckay/append-gist-action@6e8d64427fe47cbacf4ab6b890411f1d67c07f3e
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gistURL: https://gist.githubusercontent.com/EnricoMi/612cb538c14731f1a8fefe504f519395
          file: tests.svg
