name: Unit Test Results

on:
  workflow_run:
    workflows: ["CI/CD"]
    types:
      - completed

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0

  unit-test-results:
    name: Unit Test Results
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion != 'skipped' && (
        github.event.sender.login == 'dependabot[bot]' ||
        github.event.workflow_run.head_repository.full_name != github.repository
      )

    steps:
      - name: Download Artifacts
        uses: actions/github-script@v3.1.1
        with:
          script: |
            var fs = require('fs');
            var path = require('path');
            var artifacts_path = path.join('${{github.workspace}}', 'artifacts')
            fs.mkdirSync(artifacts_path, { recursive: true })

            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{ github.event.workflow_run.id }},
            });

            for (const artifact of artifacts.data.artifacts) {
               var download = await github.actions.downloadArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id,
                  archive_format: 'zip',
               });
               var artifact_path = path.join(artifacts_path, `${artifact.name}.zip`)
               fs.writeFileSync(artifact_path, Buffer.from(download.data));
               console.log(`Downloaded ${artifact_path}`);
            }
      - name: Extract Artifacts
        run: |
          for file in artifacts/*.zip
          do
            if [ -f "$file" ]
            then
              dir="${file/%.zip/}"
              mkdir -p "$dir"
              unzip -d "$dir" "$file"
            fi
          done

      - name: Publish Unit Test Results
        uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v1
        with:
          github_token: ${{ github.token }}
          commit: ${{ github.event.workflow_run.head_sha }}
          files: "artifacts/*/**/*.xml"
